#!/bin/bash
#SBATCH --job-name=mytest        # create a short name for your job
#SBATCH --nodes=1                # node count
#SBATCH --ntasks=1               # total number of tasks across all nodes
#SBATCH --cpus-per-task=1        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --time=00:20:00          # total run time limit (HH:MM:SS)
#SBATCH --partition=cpu         ## ระบุ partition ที่ต้องการใช้งาน

module load anaconda3
source activate ERAWAN_env
python hello.py
