services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./test_resources:/app/resources
    environment:
      - INPUT_DIR=/app/resources
      - OUTPUT_DIR=/app/resources
